# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(302, 163)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleEdit = QtWidgets.QLineEdit(Dialog)
        self.titleEdit.setObjectName("titleEdit")
        self.verticalLayout_2.addWidget(self.titleEdit)
        self.roastingEdit = QtWidgets.QLineEdit(Dialog)
        self.roastingEdit.setObjectName("roastingEdit")
        self.verticalLayout_2.addWidget(self.roastingEdit)
        self.groundEdit = QtWidgets.QComboBox(Dialog)
        self.groundEdit.setObjectName("groundEdit")
        self.groundEdit.addItem("")
        self.groundEdit.addItem("")
        self.verticalLayout_2.addWidget(self.groundEdit)
        self.descEdit = QtWidgets.QLineEdit(Dialog)
        self.descEdit.setObjectName("descEdit")
        self.verticalLayout_2.addWidget(self.descEdit)
        self.priceEdit = QtWidgets.QSpinBox(Dialog)
        self.priceEdit.setMaximum(999999999)
        self.priceEdit.setObjectName("priceEdit")
        self.verticalLayout_2.addWidget(self.priceEdit)
        self.volumeEdit = QtWidgets.QSpinBox(Dialog)
        self.volumeEdit.setMaximum(999999999)
        self.volumeEdit.setObjectName("volumeEdit")
        self.verticalLayout_2.addWidget(self.volumeEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.goBtn = QtWidgets.QPushButton(Dialog)
        self.goBtn.setObjectName("goBtn")
        self.horizontalLayout.addWidget(self.goBtn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nameLabel.setText(_translate("Dialog", "Название"))
        self.label.setText(_translate("Dialog", "Степень обжарки"))
        self.label_2.setText(_translate("Dialog", "Помол"))
        self.label_3.setText(_translate("Dialog", "Описание вкуса"))
        self.label_4.setText(_translate("Dialog", "Цена"))
        self.label_5.setText(_translate("Dialog", "Объем упаковки"))
        self.groundEdit.setItemText(0, _translate("Dialog", "Молотый"))
        self.groundEdit.setItemText(1, _translate("Dialog", "В зернах"))
        self.goBtn.setText(_translate("Dialog", "Добавить"))
