# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(935, 507)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(Form)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.updateBtn = QtWidgets.QPushButton(Form)
        self.updateBtn.setObjectName("updateBtn")
        self.horizontalLayout.addWidget(self.updateBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.outputCoffee = QtWidgets.QTableWidget(Form)
        self.outputCoffee.setObjectName("outputCoffee")
        self.outputCoffee.setColumnCount(0)
        self.outputCoffee.setRowCount(0)
        self.verticalLayout.addWidget(self.outputCoffee)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addButton.setText(_translate("Form", "Добавить"))
        self.updateBtn.setText(_translate("Form", "Изменить"))
